### ISSUE TITLE
Label 4.2 as broken

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/nbclient-feedstock#8]
@davidbrochart, following the yanking of 4.3, and 4.2, we should probably label 4.2 as broken on conda-forge.

cf https://github.com/jupyter/nbclient/issues/103

**Comment by davidbrochart** [comment]
Will be done when https://github.com/conda-forge/admin-requests/pull/119 is merged.

**Comment by SylvainCorlay** [comment]
Merged! Closing.
